[build]
  publish = "."
  command = "#"

[build.environment]
  PHP_VERSION = "8.0"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
  force = false
  conditions = {Path = {match = "\\.[css|js|jpg|png|gif|svg|ico|ttf|otf|woff|woff2]$"}}

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
  force = false
